import puppeteer from 'puppeteer';
import Handlebars from 'handlebars';

const templateHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #1a202c; }
    .header { text-align: center; margin-bottom: 40px; }
    .header h1 { color: #2d3748; font-size: 28px; margin: 0; }
    .header p { color: #718096; font-size: 14px; margin: 5px 0; }
    .section { margin-bottom: 30px; }
    .section h2 { color: #2d3748; border-bottom: 2px solid #4299e1; padding-bottom: 8px; font-size: 20px; }
    .info-grid { display: grid; grid-template-columns: 1.5fr 4fr; gap: 10px; margin: 15px 0; }
    .info-label { font-weight: bold; color: #4a5568; }
    .info-value { color: #2d3748; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; font-size: 13px; }
    th { background-color: #edf2f7; font-weight: 600; color: #2d3748; }
    tr:nth-child(even) { background-color: #f7fafc; }
    .gpa-section { background-color: #ebf8ff; padding: 20px; border-radius: 6px; margin-top: 20px; }
    .gpa-section h3 { color: #2c5282; margin-top: 0; }
    .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #718096; }
  </style>
</head>
<body>
  <div class="header">
    <h1>IIIT Una</h1>
    <p>Indian Institute of Information Technology Una</p>
    <p style="font-size: 18px; font-weight: bold; color: #2d3748; margin-top: 20px;">Official Academic Transcript</p>
  </div>

  <div class="section">
    <h2>Student Information</h2>
    <div class="info-grid">
      <div class="info-label">Name:</div>
      <div class="info-value">{{student.name}}</div>
      <div class="info-label">Email:</div>
      <div class="info-value">{{student.email}}</div>
      <div class="info-label">Major:</div>
      <div class="info-value">{{student.studentProfile.major}}</div>
      <div class="info-label">Enrollment Year:</div>
      <div class="info-value">{{student.studentProfile.enrollmentYear}}</div>
    </div>
  </div>

  <div class="section">
    <h2>Academic Record</h2>
    {{#if grades.length}}
    <table>
      <thead>
        <tr>
          <th>Course Code</th>
          <th>Course Title</th>
          <th>Semester</th>
          <th>Credits</th>
          <th>Grade</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {{#each grades}}
        <tr>
          <td>{{this.section.course.code}}</td>
          <td>{{this.section.course.title}}</td>
          <td>{{this.section.semester.name}}</td>
          <td>{{this.section.course.credits}}</td>
          <td><strong>{{this.letter}}</strong></td>
          <td>{{this.score}}</td>
        </tr>
        {{/each}}
      </tbody>
    </table>
    {{else}}
    <p style="color: #718096; font-style: italic;">No finalized grades available yet.</p>
    {{/if}}
  </div>

  {{#if gpa}}
  <div class="gpa-section">
    <h3>Grade Point Average</h3>
    <div class="info-grid">
      <div class="info-label">Cumulative GPA:</div>
      <div class="info-value" style="font-size: 18px; font-weight: bold; color: #2c5282;">{{gpa.cumulative}} / 10.0</div>
      <div class="info-label">Total Credits:</div>
      <div class="info-value">{{gpa.totalCredits}}</div>
    </div>
  </div>
  {{/if}}

  <div class="footer">
    <p><strong>University Management System</strong></p>
    <p>Generated on {{date}}</p>
    <p style="font-size: 10px; margin-top: 10px;">This is an official document generated by the University Management System</p>
  </div>
</body>
</html>
`;

export async function generateTranscriptPDF(student: any): Promise<Buffer> {
    // Calculate GPA (10-point scale as per IIIT Una academic regulations)
    const letterToGPA: any = {
        'S': 10, 'A': 9, 'B': 8, 'C': 7, 'D': 6, 'E': 5,
        'I': 0, 'L': 0, 'R': 0, 'M': 0, 'ABS': 0
    };

    let totalPoints = 0;
    let totalCredits = 0;

    if (student.grades && student.grades.length > 0) {
        student.grades.forEach((grade: any) => {
            const credits = grade.section.course.credits;
            const points = letterToGPA[grade.letter || 'F'] || 0;
            totalPoints += points * credits;
            totalCredits += credits;
        });
    }

    const cumulativeGPA = totalCredits > 0 ? (totalPoints / totalCredits).toFixed(2) : '0.00';

    const data = {
        student,
        grades: student.grades || [],
        gpa: {
            cumulative: cumulativeGPA,
            totalCredits
        },
        date: new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        })
    };

    const template = Handlebars.compile(templateHtml);
    const html = template(data);

    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage']
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
    });

    await browser.close();
    return Buffer.from(pdfBuffer);
}
